@startuml
title SmartHouse House Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHouse, "SmartHouse System") {
  Container(HouseService, "House Service", "Go", "Справочные данные дома")
  ContainerDb(HouseServiceDB, "Database", "PostgreSQL", "Дома")
}

Container(HouseService, "House Service", "Go") {
  Component(HouseAPI, "House API", "Управление домом")
  Component(HouseController, "House Controller", "Управление домом")
  Component(RepositoryLayer, "Repository Layer", "Логика доступа к данным")
}

Rel(HouseAPI,HouseController,"Добавление, изменение, удаление дома")
Rel(HouseController,RepositoryLayer,"Дома")
Rel(RepositoryLayer,HouseServiceDB,"Запись/чтение данных")
@enduml