@startuml
title SmartHouse Device Catalog Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHouse, "SmartHouse System") {
  Container(DeviceCatalogService, "Device Catalog Service", "Go", "Справочник поддерживаемых устройств")
  ContainerDb(DeviceCatalogServiceDB, "Database", "PostgreSQL", "Справочник устройств")
}

Container(DeviceCatalogService, "Device Catalog Service", "Go") {
  Component(DeviceCatalogAPI, "Device Catalog API", "Управление поддерживаемыми устройствами")
  Component(DeviceCatalogController, "Device Catalog Controller", "Управление поддерживаемыми устройствами")
  Component(RepositoryLayer, "Repository Layer", "Логика доступа к данным")
}

Rel(DeviceCatalogAPI,DeviceCatalogController,"Список, добавление, изменение, удаление поддерживаемых устройств")
Rel(DeviceCatalogController,RepositoryLayer,"Справочник устройств")
Rel(RepositoryLayer,DeviceCatalogServiceDB,"Запись/чтение данных")
@enduml